### ISSUE TITLE
doesn't automaticly install required packages in the venv

### ISSUE THREAD

**Issue by PimWagemans09** [avalon60/ctk_theme_builder#23]
ive tried running build_app.bat,
manually installing setuputils,
but then i get the error:
```
Collecting colorharmonies==1.0.5 (from -r requirements.txt (line 1))
  Using cached colorharmonies-1.0.5-py3-none-any.whl (3.6 kB)
Collecting colour==0.1.5 (from -r requirements.txt (line 2))
  Using cached colour-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting contourpy==1.0.5 (from -r requirements.txt (line 3))
  Using cached contourpy-1.0.5.tar.gz (12.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting CTkMessagebox==2.1 (from -r requirements.txt (line 4))
  Obtaining dependency information for CTkMessagebox==2.1 from https://files.pythonhosted.org/packages/3b/10/16187d90643dfd5a5f84dfc141c8627da3ec2a372ece5a33823c93074f72/CTkMessagebox-2.1-py3-none-any.whl.metadata
  Using cached CTkMessagebox-2.1-py3-none-any.whl.metadata (7.2 kB)
Collecting customtkinter==5.2.1 (from -r requirements.txt (line 5))
  Obtaining dependency information for customtkinter==5.2.1 from https://files.pythonhosted.org/packages/d9/22/9015be3112284c6bc5ed2ad2122d273a3c2242d5e6cbb121e027d1c77004/customtkinter-5.2.1-py3-none-any.whl.metadata
  Using cached customtkinter-5.2.1-py3-none-any.whl.metadata (652 bytes)
Collecting cycler==0.11.0 (from -r requirements.txt (line 6))
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting darkdetect==0.8.0 (from -r requirements.txt (line 7))
  Using cached darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Collecting fonttools==4.38.0 (from -r requirements.txt (line 8))
  Using cached fonttools-4.38.0-py3-none-any.whl (965 kB)
Collecting importlib-resources==5.12.0 (from -r requirements.txt (line 9))
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting kiwisolver==1.4.4 (from -r requirements.txt (line 10))
  Using cached kiwisolver-1.4.4.tar.gz (97 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting loguru==0.7.2 (from -r requirements.txt (line 11))
  Obtaining dependency information for loguru==0.7.2 from https://files.pythonhosted.org/packages/03/0a/4f6fed21aa246c6b49b561ca55facacc2a44b87d65b8b92362a8e99ba202/loguru-0.7.2-py3-none-any.whl.metadata
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting matplotlib==3.7.1 (from -r requirements.txt (line 12))
  Using cached matplotlib-3.7.1.tar.gz (38.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==1.23.4 (from -r requirements.txt (line 13))
  Using cached numpy-1.23.4.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\58147793\ctk_theme_builder\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\58147793\ctk_theme_builder\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\58147793\ctk_theme_builder\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\58147793\ctk_theme_builder\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\58147793\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\58147793\AppData\Local\Temp\pip-build-env-no3t5hdl\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\58147793\AppData\Local\Temp\pip-build-env-no3t5hdl\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\58147793\AppData\Local\Temp\pip-build-env-no3t5hdl\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by avalon60** [comment]
Which version of Python do you have installed?
Which version of Windows?

**Comment by PimWagemans09** [comment]
windows 10, version 22H2, os build 19045.3930
python 3.11.7 but i also have 3.12.1 installed the "py" and "python" commands automaticly use 3.12.1 but i have it set up that "python3117" wil use 3.11.7

**Comment by PimWagemans09** [comment]
also i just noticed when i try to change the widget geometry an empty toplevel pops up and i get the error 
```Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\58147793\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\58147793\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\58147793\ctk_theme_builder\lib\control_panel_v.py", line 948, in <lambda>
    command=lambda: self.launch_widget_geometry('CTkOptionMenu'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\58147793\ctk_theme_builder\lib\control_panel_v.py", line 1054, in launch_widget_geometry
    geometry_dialog = GeometryDialog(master=self, widget_type=widget_type,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\58147793\ctk_theme_builder\lib\geometry_dialog_v.py", line 25, in __init__
    self.enable_tooltips = mod.preference_setting(db_file_path=DB_FILE_PATH, scope='user_preference',
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib.ctk_theme_builder_m' has no attribute 'preference_setting'```

**Comment by PimWagemans09** [comment]
i start by unzipping `theme_builder_setup.py` from `ctk_theme_builder-2.5.1.zip`
i run `python3117 theme_builder_setup.py -p "C:\Users\58147793\Downloads\ctk_theme_builder-2.5.1.zip"`
usually the program would freeze here for more than an hour (thats when i decided to terminate it and run build_app.bat manually to see the output) 
but today it just worked and installed the packages in the venv

**Comment by avalon60** [comment]
I managed to get Python 3.11 installed on my development  box yesterday, and I noticed that error appear. I am not sure why it didn't appear before, but I have fixed it.  I intend to continue working this through, but I may not get any updates released until the weekend.

In the meantime, please supply the logs, there should be at least 2 in the log directory, as described in my previous post.

**Comment by PimWagemans09** [comment]
i think you are right
```
PS C:\Users\58147793\ctk_theme_builder> .\venv\scripts\activate
(venv) PS C:\Users\58147793\ctk_theme_builder> python --version
Python 3.12.1```

**Comment by avalon60** [comment]
So, it looks like the path to your Python 3.12 installation, appears on your Windows %PATH% variable before your Python 3.11 install. You could confirm this by typying `echo %PATH%`, and pressing enter. This means that Python 3.12 is getting seeded to the virtual environment folder (venv). You could uninstall Python 3.12, and remove the `ctk_theme_builder` directory where you installed to and then retry the install process. The other option, is to try this: 
[ctk_theme_builder-3.0.0.zip](https://github.com/avalon60/ctk_theme_builder/files/14350921/ctk_theme_builder-3.0.0.zip)

1. Remove the old `ctk_theme_builder` directory;
2. Extract the `theme_builder_setup.py` file;
3. Run the install as described previously.

The 3.0.0 file, includes an update of all the libraries. It installs aginst Python 3.12 on Linux Mint, just fine. I haven't tried it on Windows, and so that's where you come in. Please let me know how you get on.

**Comment by PimWagemans09** [comment]
I will try that  but i just noticed that you asked for the logs. Do you still need them?

**Comment by PimWagemans09** [comment]
ive installed it using 3.11.7
it seems to have installed the packages correctly
but this erro still occurs when trying to change widget geometry
```Traceback (most recent call last):
  File "C:\Users\58147793\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\58147793\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\58147793\ctk_theme_builder\lib\control_panel_v.py", line 948, in <lambda>
    command=lambda: self.launch_widget_geometry('CTkOptionMenu'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\58147793\ctk_theme_builder\lib\control_panel_v.py", line 1054, in launch_widget_geometry
    geometry_dialog = GeometryDialog(master=self, widget_type=widget_type,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\58147793\ctk_theme_builder\lib\geometry_dialog_v.py", line 25, in __init__
    self.enable_tooltips = mod.preference_setting(db_file_path=DB_FILE_PATH, scope='user_preference',
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib.ctk_theme_builder_m' has no attribute 'preference_setting'```

**Comment by avalon60** [comment]
> ive installed it using 3.11.7 it seems to have installed the packages correctly but this error still occurs when trying to change widget geometry
> 
> ```
>   File "C:\Users\58147793\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\58147793\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
>     self._command()
>   File "C:\Users\58147793\ctk_theme_builder\lib\control_panel_v.py", line 948, in <lambda>
>     command=lambda: self.launch_widget_geometry('CTkOptionMenu'))
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\58147793\ctk_theme_builder\lib\control_panel_v.py", line 1054, in launch_widget_geometry
>     geometry_dialog = GeometryDialog(master=self, widget_type=widget_type,
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\58147793\ctk_theme_builder\lib\geometry_dialog_v.py", line 25, in __init__
>     self.enable_tooltips = mod.preference_setting(db_file_path=DB_FILE_PATH, scope='user_preference',
>                            ^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'lib.ctk_theme_builder_m' has no attribute 'preference_setting'```
> ```

Please double check the Python version using:

```
venv\scripts\activate.bat
python --version
```

If you look at the path: `">   File "C:\Users\58147793\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__"`
It references Python 3.12. 

1. Did you use the Beta version, 3.0.0, zip file that I supplied?
2. Did you remove the previous install location (the ctk_theme_builder directory) before retrying?

**Comment by PimWagemans09** [comment]
```
PS C:\Users\58147793\ctk_theme_builder> .\venv\scripts\activate
(venv) PS C:\Users\58147793\ctk_theme_builder> python --version
Python 3.12.1
(venv) PS C:\Users\58147793\ctk_theme_builder>
```
i used 3.0.0 and i removed the old ctk_theme_builder directory

**Comment by PimWagemans09** [comment]
i run `theme_builder_setup.py` with this command 
` python3117 theme_builder_setup.py -p "C:\Users\58147793\Downloads\ctk_theme_builder-3.0.0.zip"`
as i said [here](https://github.com/avalon60/ctk_theme_builder/issues/23#issuecomment-1942947558) the command `python` uses python 3.12.1 and `python3117` uses 3.11.7

**Comment by PimWagemans09** [comment]
logs : [log.zip](https://github.com/avalon60/ctk_theme_builder/files/14364987/log.zip)
theme_builder_setup.py output:
[theme_builder_setup.txt](https://github.com/avalon60/ctk_theme_builder/files/14365004/theme_builder_setup.txt)
ctk_theme_builder_output:
```Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\58147793\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\58147793\ctk_theme_builder\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\58147793\ctk_theme_builder\lib\control_panel_v.py", line 869, in <lambda>
    command=lambda: self.launch_widget_geometry('CTkButton'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\58147793\ctk_theme_builder\lib\control_panel_v.py", line 1054, in launch_widget_geometry
    geometry_dialog = GeometryDialog(master=self, widget_type=widget_type,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\58147793\ctk_theme_builder\lib\geometry_dialog_v.py", line 25, in __init__
    self.enable_tooltips = mod.preference_setting(db_file_path=DB_FILE_PATH, scope='user_preference',
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib.ctk_theme_builder_m' has no attribute 'preference_setting'
```

**Comment by avalon60** [comment]
> i run `theme_builder_setup.py` with this command ` python3117 theme_builder_setup.py -p "C:\Users\58147793\Downloads\ctk_theme_builder-3.0.0.zip"` as i said [here](https://github.com/avalon60/ctk_theme_builder/issues/23#issuecomment-1942947558) the command `python` uses python 3.12.1 and `python3117` uses 3.11.7

If you have removed 3.12 Python,  something very odd is happening. It appears that it is still, somehow, picking up Python 3.12. The theme_builder_setup.py, makes an OS call to a execute a BAT file which also calls Python to create a virtual  environment, it is that which appears to be picking up Python 3.12, so I am guessing that is still sitting around, and is on your Windows %PATH%, appearing before the entry for Python 3.11.

All this is academic, to some extent. I installed Python 3.12 on my laptop tonight, and used the 3.0.0 zip to try an install. Again it went fine. I am starting to think that something has gone awry on your computer. I'll take a look at the logs, but I am doubtful of a resolution, without direct hands-on.

**Comment by avalon60** [comment]
> logs : [log.zip](https://github.com/avalon60/ctk_theme_builder/files/14364987/log.zip) theme_builder_setup.py output: [theme_builder_setup.txt](https://github.com/avalon60/ctk_theme_builder/files/14365004/theme_builder_setup.txt) ctk_theme_builder_output:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\58147793\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\58147793\ctk_theme_builder\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
>     self._command()
>   File "C:\Users\58147793\ctk_theme_builder\lib\control_panel_v.py", line 869, in <lambda>
>     command=lambda: self.launch_widget_geometry('CTkButton'))
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\58147793\ctk_theme_builder\lib\control_panel_v.py", line 1054, in launch_widget_geometry
>     geometry_dialog = GeometryDialog(master=self, widget_type=widget_type,
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\58147793\ctk_theme_builder\lib\geometry_dialog_v.py", line 25, in __init__
>     self.enable_tooltips = mod.preference_setting(db_file_path=DB_FILE_PATH, scope='user_preference',
>                            ^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'lib.ctk_theme_builder_m' has no attribute 'preference_setting'
> ```

Strange, I can't see any problems in the logs. Does it still error with a timeout?

**Comment by PimWagemans09** [comment]
> If you have removed 3.12 Python, something very odd is happening. It appears that it is still, somehow, picking up Python 3.12. The theme_builder_setup.py, makes an OS call to a execute a BAT file which also calls Python to create a virtual environment, it is that which appears to be picking up Python 3.12, so I am guessing that is still sitting around, and is on your Windows %PATH%, appearing before the entry for Python 3.11.
> 
> All this is academic, to some extent. I installed Python 3.12 on my laptop tonight, and used the 3.0.0 zip to try an install. Again it went fine. I am starting to think that something has gone awry on your computer. I'll take a look at the logs, but I am doubtful of a resolution, without direct hands-on.

I havnt tried removing 3.12 yet thats the next thing i will try

**Comment by PimWagemans09** [comment]
> Strange, I can't see any problems in the logs. Does it still error with a timeout?

No and this problem doesnt crash the program only (what i presume to be) the widget geometry editor

**Comment by PimWagemans09** [comment]
so i removed python 3.12.1 from %path% and added 3.11.7 so now the  `python` command will use 3.11.7
... the venv version is still 3.12.1

**Comment by PimWagemans09** [comment]
i have deleted 3.12.1 completely (its stil in the recycle bin) and it doesnt create a venv at all
[theme_builder_setup_2024-02-22_10-25-02.log](https://github.com/avalon60/ctk_theme_builder/files/14371847/theme_builder_setup_2024-02-22_10-25-02.log)

**Comment by avalon60** [comment]
> > Strange, I can't see any problems in the logs. Does it still error with a timeout?
> 
> No and this problem doesnt crash the program only (what i presume to be) the widget geometry editor Al the other problems i was heving are fixed

I have reproduced your problem - leave it with me.

**Comment by avalon60** [comment]
I think I have a fix - I'll get it published asap.
Thanks for your patience on this.

**Comment by avalon60** [comment]
Hi @PimWagemans09. Justto let you know, these should now be fixed with. Please see [CTk Theme Builder Release 3.0.1 ](https://github.com/avalon60/ctk_theme_builder/releases/tag/v3.0.1).

Thanks for you persistence and patience, in getting to the bottom of these - much appreciated!

**Comment by PimWagemans09** [comment]
im glad i could help!
the issues are indeed gone now 
i gues this issue can be closed now
